name: Node.js CI/CD Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    build-and-test:
        runs-on: ubuntu-latest
    
        strategy:
            matrix:
                node-version: [16.x, 18.x, 20.x]
        
        steps:
        - uses: actions/checkout@v3
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
        
        - name: Install Dependencies
          run: npm ci
        
        - name: Run Tests
          run: npm test
        
    
    build-and-deploy:
        needs: build-and-test
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'

        steps:
        - name: Deploy to Production Server
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USERNAME }}
            key: ${{ secrets.DEPLOY_SSH_KEY }}
            script: |
              export MONGODB_URI=${{ secrets.MONGODB_URI }}
              export PORT=${{ secrets.PORT }}
              cd /home/deployer/code/backend
              git pull
              /home/deployer/.nvm/versions/node/v18.18.2/bin/npm ci
              /home/deployer/.nvm/versions/node/v18.18.2/bin/npm install 
              /home/deployer/.nvm/versions/node/v18.18.2/bin/pm2 restart all